config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "spends#total"

  resources :spends do
    get 'total', on: :collection
  end

  resources :categories
  resources :sources
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(position: :desc, id: :desc) }
end

app/models/source.rb
class Source < ApplicationRecord
  default_scope { order(position: :desc, id: :desc) }
end

app/models/spend_item.rb
class SpendItem < ApplicationRecord
  belongs_to :category, optional: true
  belongs_to :source, optional: true
  belongs_to :target, optional: true, class_name: 'Source'

  attr_accessor :like, :replenishment

  before_save :negative_amount, if: :replenishment?
  after_save :change_source_amount
  after_destroy :revert_source_amount

  default_scope { order(created_at: :desc) }

  private

  def replenishment?
    replenishment.to_i == 1
  end

  def negative_amount
    self.amount = -amount
  end

  def change_source_amount
    return unless amount_previously_changed? || source_id_previously_changed? || target_id_previously_changed?

    if source_id_previously_changed?
      source_was = Source.find_by(id: source_id_previously_was)
      source_was&.update(amount: source_was.amount + amount_previously_was)
    else
      self.source&.update(amount: source.amount + amount_previously_was) if amount_previously_changed?
    end

    if target_id_previously_changed?
      target_was = Source.find_by(id: target_id_previously_was)
      target_was&.update(amount: target_was.amount - amount_previously_was)
    end

    self.source&.update(amount: source.amount - amount)
    self.target&.update(amount: target.amount + amount)
  end

  def revert_source_amount
    self.source&.update(amount: source.amount + amount)
    self.target&.update(amount: target.amount - amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_spend

  private

  def set_spend
    @spend = SpendItem.new
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
    @category = if params[:category_id]
            category = Category.find(params[:category_id])
            category.like = 1 if category.like_id
          else
            Category.new
          end
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      render "index"
    end
  end

  def update
    @category = Category.find(params[:id])
    @category.assign_attributes(category_params)

    if @category.save
      redirect_to categories_path
    else
      render "index"
    end
  end

  def destroy
    Category.find(params[:id]).destroy

    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:title, :position)
  end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  def index
    @sources = Source.all
    @source = if params[:source_id]
                source = Source.find(params[:source_id])
              else
                Source.new
              end
  end

  def create
    @source = Source.new(source_params)

    if @source.save
      redirect_to sources_path
    else
      render "index"
    end
  end

  def update
    @source = Source.find(params[:id])
    @source.assign_attributes(source_params)

    if @source.save
      redirect_to sources_path
    else
      render "index"
    end
  end

  def destroy
    Source.find(params[:id]).destroy

    redirect_to sources_path
  end

  private

  def source_params
    params.require(:source).permit(:title, :amount, :position)
  end
end

app/controllers/spends_controller.rb
class SpendsController < ApplicationController
  before_action :authenticate_user!

  def index
    @spends = SpendItem.all
    @spend = if params[:spend_id]
               spend = SpendItem.find(params[:spend_id])
               spend.like = '1' if spend.like_id
               spend
             else
               SpendItem.new
             end
    @categories = Category.pluck(:title, :id)
    @sources = Source.pluck(:id, :title).to_h
    first_spend = @spends.first&.created_at
    @last_time = if first_spend && first_spend.day < Time.zone.now.day || first_spend.month < Time.zone.now.month
                   first_spend + 1.minute
                 end
  end

  def total
    @categories = Category.pluck(:title, :id)
    @sources = Source.all

    @grouped_items = SpendItem.all
                              .group_by { |item| item.created_at.strftime('%m-%y') }
                              .transform_values do |group_by_date|
      group_by_date.group_by { |item| @categories.find { |category| category.last == item.category_id }&.first }
                   .transform_values do |group_by_category|
        group_by_category.sum do |item|
          item.amount > 0 && !item.target_id ? item.amount : 0
        end
      end
    end

    @grouped_earnings = SpendItem.all
                                 .group_by { |item| item.created_at.strftime('%m-%y') }
                                 .transform_values do |group_by_date|
      group_by_date.sum { |item| item.amount < 0 && !item.target_id ? -item.amount : 0 }
    end

    date = params[:date].present? && Time.zone.parse(params[:date])
    @month = params[:month] || (date || Time.zone.now).strftime('%m-%y')
  end

  def create
    @spend_item = SpendItem.new(spend_item_params)
    @spend_item.like_id = spend_item_params[:like].to_i == 1 ? current_user.id : nil

    if spend_item_params[:source_id] == spend_item_params[:target_id]
      flash[:notice] = 'перевод на источник'
      redirect_to(spends_path)
      return
    end

    if @spend_item.save
      redirect_to spends_path
    else
      render "index"
    end
  end

  def update
    @spend_item = SpendItem.find(params[:id])
    @spend_item.assign_attributes(spend_item_params)
    @spend_item.like_id = spend_item_params[:like].to_i == 1 ? current_user.id : nil

    if @spend_item.save
      redirect_to spends_path
    else
      render "index"
    end
  end

  def destroy
    SpendItem.find(params[:id]).destroy

    redirect_to spends_path
  end

  private

  def spend_item_params
    params.require(:spend_item)
          .permit(:title, :category_id, :amount, :source_id, :target_id, :like, :created_at, :replenishment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/spends_helper.rb
module SpendsHelper
end

app/views/categories/index.html.erb
<div class="wrapper">
  <div class="container">
    <%= render "devise/shared/error_messages", resource: @category %>

    <h1>Категории</h1>

    <table class="table">
      <tr>
        <th>Дата</th>
        <th>Категория</th>
        <th></th>
      </tr>

      <% @categories.each do |category| %>
        <tr>
          <td><%= category.created_at.strftime('%d.%m') %></td>
          <td><%= category.title %></td>
          <td>
            <%= link_to 'Изм', categories_path(category_id: category.id) %>
            <%= link_to 'Удл', category_path(category), data: { turbo_method: :delete } %>
          </td>
        </tr>
      <% end %>
    </table>

    <button class="btn" data-toggle="modal" data-target="categoryModal">Добавить</button>
  </div>
</div>

<%= render 'layouts/modal_category' %>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="container header__inner">
    <%= image_tag '4.gif' %>
    <ul class="menu">
        <li><%= link_to 'Траты', spends_path, class: 'btn' %></li>
        <li><%= link_to 'Категории', categories_path, class: 'btn' %></li>
        <li><%= link_to 'Источники', sources_path, class: 'btn' %></li>
        <li><button class="btn" data-toggle="modal" data-target="spendModal">Потратить</button></li>
        <li><%= link_to 'Сводная таблица', total_spends_path, class: 'btn', data: { turbo: false } %></li>
        <% if current_user %>
          <li><%= link_to 'Выход', destroy_user_session_path, class: 'btn', method: :delete %></li>
        <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_modal.html.erb
<div class="modal-wrapper" id="spendModal" data-controller="modal">
  <div class="modal spend-modal">
    <h2>Добавить траты</h2>

    <%= form_for(@spend, url: params[:spend_id] ? spend_path(@spend) : spends_path, html: { class: 'appear', method: (params[:spend_id] ? :put : :post) }) do |f| %>
      <div>
        <%= f.label :amount, 'Сумма' %>
        <%= f.number_field :amount %>
      </div>

      <div>
          <%= f.label :title, 'Название' %>
          <%= f.text_field :title %>
      </div>

      <div>
        <%= f.label :category_id, 'Категория' %>
        <%= f.select :category_id, Category.pluck(:title, :id), include_blank: true %>
      </div>

      <div>
        <%= f.label :source_id, 'Источник' %>
        <%= f.select :source_id, Source.all.map { |source| ["#{source.title} #{source.amount}р.", source.id] } %>
      </div>

      <div>
        <%= f.label :like %>
        <%= f.checkbox :like %>
      </div>

      <div>
        <%= f.label :replenishment, 'Пополнение' %>
        <%= f.checkbox :replenishment %>
      </div>

      <div>
        <%= f.label :created_at, 'Дата траты' %>
        <%= f.datetime_select :created_at, default: @last_time || Time.zone.now %>
      </div>

      <div>
        <%= f.label :target_id, 'Источник получения средств' %>
        <%= f.select :target_id, Source.all.map { |source| ["#{source.title} #{source.amount}р.", source.id] }, include_blank: true %>
      </div>

      <%= f.submit params[:spend_id] ? 'Применить' : 'Добавить', class: 'btn' %>
    <% end %>
  </div>      
</div>

app/views/layouts/_modal_category.html.erb
<div class="modal-wrapper" id="categoryModal" data-controller="modal">
  <div class="modal spend-modal">
    <h2>Добавить категорию</h2>

    <%= form_for(@category, url: params[:category_id] ? category_path(@category) : categories_path, html: { class: 'appear', method: (params[:category_id] ? :put : :post) }) do |f| %>
      <div>
          <%= f.label :title, 'Название' %>
          <%= f.text_field :title %>
      </div>

      <div>
        <%= f.label :position, 'Порядковый номер' %>
        <%= f.number_field :position %>
      </div>

      <%= f.submit params[:category_id] ? 'Применить' : 'Добавить', class: 'btn' %>
    <% end %>
  </div>      
</div>

app/views/layouts/_modal_source.html.erb
<div class="modal-wrapper" id="sourceModal" data-controller="modal">
  <div class="modal spend-modal">
    <h2>Добавить источник</h2>

    <%= form_for(@source, url: params[:source_id] ? source_path(@source) : sources_path, html: { class: 'appear', method: (params[:source_id] ? :put : :post) }) do |f| %>
      <div>
          <%= f.label :title, 'Название' %>
          <%= f.text_field :title %>
      </div>

      <div>
        <%= f.label :amount, 'Баланс' %>
        <%= f.number_field :amount %>
      </div>

      <div>
        <%= f.label :position, 'Порядковый номер' %>
        <%= f.number_field :position %>
      </div>

      <%= f.submit params[:source_id] ? 'Применить' : 'Добавить', class: 'btn' %>
    <% end %>
  </div>      
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Spend" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <% flash.each do |name, msg| %>
    <div class='flash'>
      <%= content_tag :div, msg, class: name %>
      <span class="flash-close">x</span>
    </div>
    <% end %>

    <%= yield %>

    <%= render 'layouts/modal' %>

    <%= javascript_include_tag 'init.js' %>
  </body>
</html>

app/views/sources/index.html.erb
<div class="wrapper">
  <div class="container">
    <%= render "devise/shared/error_messages", resource: @source %>

    <h1>Источники</h1>

    <table class="table">
      <tr>
        <th>Дата</th>
        <th>Источник</th>
        <th>Баланс</th>
        <th></th>
      </tr>

      <% @sources.each do |source| %>
        <tr>
          <td><%= source.created_at.strftime('%d.%m') %></td>
          <td><%= source.title %></td>
          <td><%= source.amount %>р.</td>
          <td>
            <%= link_to 'Изм', sources_path(source_id: source.id) %>
            <%= link_to 'Удл', source_path(source), data: { turbo_method: :delete } %>
          </td>
        </tr>
      <% end %>
    </table>

    <button class="btn" data-toggle="modal" data-target="sourceModal">Добавить</button>
  </div>
</div>

<%= render 'layouts/modal_source' %>

app/views/spends/index.html.erb
<div class="wrapper">
  <div class="container">
    <%= render "devise/shared/error_messages", resource: @spend %>

    <h1>Траты</h1>

    <table class="table">
      <tr>
          <th>Дата</th>
          <th>Наименование</th>
          <th>Категория</th>
          <th>Сумма</th>
          <th>Источник</th>
          <th></th>
      </tr>

      <% @spends.each do |spend| %>
        <tr>
            <td><%= spend.created_at.strftime('%d.%m') %></td>
            <td><%= spend.title %></td>
            <td><%= @categories.find { _1.last == spend.category_id }&.first %></td>
            <td style="<%= 'background-color: #a3a300;' if spend.amount < 0 %>"><%= spend.amount.abs %></td>
            <td>
              <%= @sources[spend.source_id] %>
              <% if spend.target_id %>
              -> <%= @sources[spend.target_id] %>
              <% end %>
            </td>
            <td>
              <%= spend.like_id %>
              <%= link_to 'Изм', spends_path(spend_id: spend.id) %>
              <%= link_to 'Удл', spend_path(spend), data: { turbo_method: :delete } %>
            </td>
        </tr>
      <% end %>
    </table>

    <form class="search" action="/">
        <div class="row">
            <div class="form-group">
                <input type="text" id="писун" placeholder="найти...">
            </div>       
        </div>
    </form>
  </div>      
</div>      

app/views/spends/total.html.erb
<div class="wrapper" data-controller="charts">
  <div class="container">
    <h1>Итоги</h1>

    <ul style="display: flex;list-style-type: none;">
      <% @sources.each do |source| %>
        <li style="margin-right: 10px;"><%= source.title %> <%= source.amount %></li>
      <% end %>
    </ul>

    <table class="table">
      <% @grouped_items.each do |date, by_date| %>
        <tr>
          <th>Месяц</th>
          <% by_date.keys.each do |category| %>
            <th><%= category %></th>
          <% end %>
          <th>Итого</th>
        </tr>

        <tr>
          <td><%= date %></td>
          <% by_date.each do |category, by_category| %>
            <td><%= by_category %>р.</td>
          <% end %>
          <td><%= by_date.values.sum %>р.</td>
        </tr>
      <% end %>
    </table>

    <ul class="menu date-btn">
      <li>
        <%= form_tag total_spends_path(), method: :get, turbo: true, data: { turbo: true, turbo_stream: true } do %>
          <%= label_tag :date, 'Выбрать месяц' %>
          <%= date_field_tag :date, params[:date] %>
          <%= submit_tag 'Применить' %>
        <% end %>
      </li>
    </ul>

    <h2>Траты по категориям за месяц</h2>
    <div class="chart"> 
        <canvas id="chart2"></canvas>
    </div>

    <h2>Траты/доход по месяцам</h2>
    <div class="chart">
        <canvas id="chart1"></canvas>
    </div>
  </div>
</div>

<script data-turbo-track="reload">
  const chart1labels = <%= raw @grouped_items.keys.to_json %>;
  const chart1data = <%= raw @grouped_items.values.map { |by_date| by_date.values.sum }.to_json %>;
  const chart1data2 = <%= raw @grouped_items.keys.map { |date| @grouped_earnings[date] }.to_json %>;
  const chart2labels = <%= raw Array.wrap(@grouped_items[@month]&.keys).to_json %>;
  const chart2data = <%= raw Array.wrap(@grouped_items[@month]&.values).to_json %>;
</script>

<%= javascript_include_tag 'chart.js', "data-turbo-track": "reload" %>